### ISSUE TITLE
[Discussion] no_std support

### ISSUE THREAD

**Issue by SimonIT** [primetype/cbor_event#12]
Hey @NicolasDP,
@connectety and I want to use cddl-codegen with constrained devices.
For this, we need `no_std` compatibility.
We started making the changes in [our fork](https://github.com/SimonIT/cbor_event/tree/no_std).

It seems that everything is compatible with `no_std` except `BufRead`.
For `BufRead` exists a drop-in replacement called [acid_io](https://github.com/dataphract/acid_io).

So I want to get some opinions from you maintainers about this.
Especially because of your statement:
> this crate has zero dependencies (and should not need any in the future)

**Comment by NicolasDP** [comment]
hello @SimonIT , thanks for the effort in adding no_std support to the crate. I believe you are adding this so that you can use the output of the `cddl_codegen` to add cardano support on hardware wallets.

The `acid_io` crate is interesting though I am not sure this is the approach I would have looked at first. I think we should consider a rework of the core component to add the right type of support. I'd like to offer another approach instead:

please have a look at the following: https://github.com/primetype/cbor_event/pull/14

This way the array and bytes data are completely left to the user of the crates and we don't need the BufRead dependency. What do you think?

**Comment by SimonIT** [comment]
Good idea.

Another problem I came across is the error handling:

1. The trait `Error` in `core` is not stable rust-lang/rust#103765
2. Because the trait is not sized, something like `Box` has to be used
   https://github.com/primetype/cbor_event/blob/b086ad463f5ad89443631852d54193e3e495f4a9/src/error.rs#L33
   This is kinda ugly in my opinion.
3. There seem to be a problem with thread safety and errors?
```
  error[E0277]: `(dyn core::error::Error + 'static)` cannot be sent between threads safely
   --> src/de.rs:23:17
    |
    23 |             Err(Box::new(Error::ExpectedU8))
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ `(dyn core::error::Error + 'static)` cannot be sent between threads safely
    |
    = help: the trait `Send` is not implemented for `(dyn core::error::Error + 'static)`
    = note: required for `Unique<(dyn core::error::Error + 'static)>` to implement `Send`
    = note: required because it appears within the type `Box<dyn Error>`
   note: required because it appears within the type `Error`
   --> src/error.rs:11:10
    |
   11 | pub enum Error {
    |          ^^^^^
    = note: required for the cast from `error::Error` to the object type `dyn core::error::Error + Send + Sync`
```

**Comment by NicolasDP** [comment]
if we go the path I'm suggesting we don't need `IO` anymore. We will not need to do things like `IoError(Box<dyn error::Error>)`.

**Comment by SimonIT** [comment]
We think everything is resolved.  Our PR is working. Feel free to make some suggestions there #13 .
